[tools]
chezmoi = "latest"
fd = "latest"
fzf = "latest"
gum = "latest"
node = "24"
"npm:tree-sitter-cli" = "latest"
ripgrep = "latest"
starship = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
python.uv_venv_auto = true
experimental=true
