[tools]
starship = "latest"
fzf = "latest"
fd = "latest"
ripgrep = "latest"
zoxide = "latest"
gum = "latest"
node = "latest"
"npm:tree-sitter-cli" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
python.uv_venv_auto = true
experimental=true
